### ISSUE TITLE
Install error: "Missing C libraries: Xrandr, Xcursor, Xinerama"

### ISSUE THREAD

**Issue by SolviQorda** [Mokosha/Lambency#16]
Followed the build instructions in the Readme and got the following error:

> Configuring bindings-GLFW-3.2.1.1...
> Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependencies on foreign
> libraries:
> * Missing C libraries: Xrandr, Xcursor, Xinerama
> This problem can usually be solved by installing the system packages that
> provide these libraries (you may need the "-dev" versions). If the libraries
> are already installed but in a non-standard location then you can use the
> flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
> 

have installed the relevant libraries with apt. May just be a one-off but thought it might be useful to flag!

**Comment by Mokosha** [comment]
Thanks for the heads up.  All of those packages are dependencies of [`bindings-GLFW`](https://github.com/bsl/bindings-GLFW), so the extra include dirs shouldn't be necessary unless, as the warning says, they're in non-standard locations (in which case they shouldn't go in the stack.yaml).

The README is out of date though so I'll update that.
